root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - prettier
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@next/next/recommended
  - plugin:prettier/recommended
rules:
  '@typescript-eslint/consistent-type-imports': error
  'prettier/prettier':
    - error
    - endOfLine: auto
